[package]
name = "audio-visualization"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.22.0"
lofty = "0.14.0"
rfd = "0.11.4"
rodio = "0.17.1"
rustfft = "6.1.0"
